### ISSUE TITLE
failure to push the update to github

### ISSUE THREAD

**Issue by vlin3** [vlin3/SEBC#2]
after update the README.md file on local and try to push to GitHub, got the following error
"error: src refspec sebc-shanghai-2017 does not match any" 
error: failed to push some refs to 'https://github.com/vlin3/SEBC.git'

**Comment by mfernest** [comment]
You don't have the branch `sebc-shanghai-2017` created on GitHub. Write to the `master` branch instead.

**Comment by vlin3** [comment]
![Uploading failure to sync file.png…]()

I try but seems the update didn't upload yet. Is my command correct?
